---
deployment:
  tasks:
    - export BASEPATH=/home/pekesc5/public_html/informes
    # Asegurar permisos de carpeta raiz
    - chmod 755 $BASEPATH
    # Crear estructura de carpetas
    - /bin/mkdir -p $BASEPATH/comercial-hidrobo/marzo-2026
    - /bin/mkdir -p $BASEPATH/global-trading/marzo-2026
    - chmod 755 $BASEPATH/comercial-hidrobo
    - chmod 755 $BASEPATH/global-trading
    # Deploy Comercial Hidrobo
    - /bin/cp -f comercial-hidrobo/marzo-2026/.htaccess $BASEPATH/comercial-hidrobo/marzo-2026/
    - /bin/cp -f comercial-hidrobo/marzo-2026/index.php $BASEPATH/comercial-hidrobo/marzo-2026/
    - /bin/cp -f comercial-hidrobo/marzo-2026/login.php $BASEPATH/comercial-hidrobo/marzo-2026/
    - /bin/cp -f comercial-hidrobo/marzo-2026/logout.php $BASEPATH/comercial-hidrobo/marzo-2026/
    # Deploy Global Trading
    - /bin/cp -f global-trading/marzo-2026/.htaccess $BASEPATH/global-trading/marzo-2026/
    - /bin/cp -f global-trading/marzo-2026/index.php $BASEPATH/global-trading/marzo-2026/
    - /bin/cp -f global-trading/marzo-2026/login.php $BASEPATH/global-trading/marzo-2026/
    - /bin/cp -f global-trading/marzo-2026/logout.php $BASEPATH/global-trading/marzo-2026/
    # Permisos
    - chmod 755 $BASEPATH/comercial-hidrobo/marzo-2026
    - chmod 755 $BASEPATH/global-trading/marzo-2026
    - chmod 644 $BASEPATH/comercial-hidrobo/marzo-2026/*.php
    - chmod 644 $BASEPATH/global-trading/marzo-2026/*.php
    # Crear estructura Luuma
    - /bin/mkdir -p $BASEPATH/luuma/marzo-2026
    - chmod 755 $BASEPATH/luuma
    # Deploy Luuma
    - /bin/cp -f luuma/marzo-2026/.htaccess $BASEPATH/luuma/marzo-2026/
    - /bin/cp -f luuma/marzo-2026/index.php $BASEPATH/luuma/marzo-2026/
    - /bin/cp -f luuma/marzo-2026/login.php $BASEPATH/luuma/marzo-2026/
    - /bin/cp -f luuma/marzo-2026/logout.php $BASEPATH/luuma/marzo-2026/
    # Permisos Luuma
    - chmod 755 $BASEPATH/luuma/marzo-2026
    - chmod 644 $BASEPATH/luuma/marzo-2026/*.php
    # Crear estructura Odontologia Life
    - /bin/mkdir -p $BASEPATH/odontologia-life/marzo-2026
    - chmod 755 $BASEPATH/odontologia-life
    # Deploy Odontologia Life
    - /bin/cp -f odontologia-life/marzo-2026/.htaccess $BASEPATH/odontologia-life/marzo-2026/
    - /bin/cp -f odontologia-life/marzo-2026/index.php $BASEPATH/odontologia-life/marzo-2026/
    - /bin/cp -f odontologia-life/marzo-2026/login.php $BASEPATH/odontologia-life/marzo-2026/
    - /bin/cp -f odontologia-life/marzo-2026/logout.php $BASEPATH/odontologia-life/marzo-2026/
    # Permisos Odontologia Life
    - chmod 755 $BASEPATH/odontologia-life/marzo-2026
    - chmod 644 $BASEPATH/odontologia-life/marzo-2026/*.php
